package com.example.ui

import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.format.DateTimeFormatter
import java.util.Locale

object Localization {
    private val ru = mapOf(
        "dashboard_tab" to "Дашборд",
        "shifts_tab" to "Смены",
        "reports_tab" to "Отчеты",
        "settings_tab" to "Настройки",
        "welcome_title" to "Привет, %s!",
        "welcome_subtitle" to "Учёт рабочего времени • Режим труда и отдыха ЕС",
        "week_report_title" to "Недельный отчет",
        "no_shifts_period" to "Нет смен за этот период",
        "add_shift_btn" to "Добавить смену",
        "weekly_limits_title" to "Лимиты на неделю (Регламент ЕС № 561/2006):",
        "limit_shifts_13h" to "Смены > 13ч",
        "limit_driving_9h" to "Вождение > 9ч",
        "limit_rest_11h" to "Отдых < 11ч",
        "limit_exceeded" to "Превышен!",
        "limit_normal" to "Норма",
        "totals_title" to "Итоговые показатели",
        "metric_driving" to "Времени за рулем",
        "metric_expenses" to "Сумма расходов",
        "metric_regular_shifts" to "Обычные смены",
        "metric_tacho_shifts" to "Смены по тако",
        "metric_nights" to "Ночевок в пути",
        "nights_count" to "%d ноч.",
        "registered_shifts_week" to "Зарегистрированные смены этой недели:",
        "regular_shift_label" to "Обычная смена:",
        "tacho_label" to "Тако:",
        "driving_label" to "Вождение:",
        "duration_label" to "Длительность:",
        "night_on_road" to "Ночь в дороге",
        "night_at_home" to "Домашняя ночь",
        "edit_btn" to "Редактировать",
        "delete_btn" to "Удалить",
        "delete_dialog_title" to "Удалить смену?",
        "delete_dialog_text" to "Вы уверены, что хотите безвозвратно удалить смену за %s из журнала?",
        "cancel_btn" to "Отмена",
        "shifts_log_title" to "Журнал смен (%d)",
        "shifts_log_empty" to "Журнал пуст. Внесите свою первую рабочую смену!",
        "add_shift_action" to "Внести смену",
        "reports_title" to "Сводные отчеты",
        "reports_range_label" to "Диапазон дат для отчета:",
        "reports_start_label" to "Начало периода",
        "reports_end_label" to "Конец периода",
        "text_report_title" to "Текстовый отчет для отправки",
        "text_report_desc" to "Удобно скопировать для отправки диспетчеру через мессенджеры или почту.",
        "copy_report_btn" to "Скопировать отчет",
        "preview_report_title" to "Предпросмотр отчета:",
        "toast_report_copied" to "Отчет скопирован в буфер обмена!",
        "toast_profile_saved" to "Настройки успешно сохранены!",
        "settings_title" to "Настройки",
        "settings_profile_section" to "Профиль водителя",
        "settings_driver_name" to "Имя водителя",
        "settings_save_btn" to "Сохранить",
        "settings_lang_section" to "Выбор языка / Language Selection",
        "settings_lang_ru" to "Русский (RU)",
        "settings_lang_en" to "English (EN)",
        "settings_mode_section" to "Режим работы приложения",
        "settings_mode_extended" to "Расширенный (смена + тахограф)",
        "settings_mode_shortened" to "Сокращённый (только тахограф)",
        "settings_docs_section" to "Регламент ЕС № 561/2006",
        "settings_docs_subtitle" to "Основные нормативы ЕС для грузовых перевозок:",
        "settings_doc_tacho_title" to "Максимальная смена тако (Tacho Shift):",
        "settings_doc_tacho_desc" to "Стандартная смена составляет 13 часов. Ограничение может превышать 13 часов (но до 15 часов) не более 3 раз за рабочую неделю.",
        "settings_doc_driving_title" to "Максимальное вождение за сутки:",
        "settings_doc_driving_desc" to "Стандартный дневной лимит составляет 9 часов. Допускается увеличение вождения до 10 часов не более 2 раз за рабочую неделю.",
        "settings_doc_rest_title" to "Ежедневный отдых:",
        "settings_doc_rest_desc" to "Регулярный отдых составляет не менее 11 часов подряд между рабочими сменами. Отдых менее 11 часов (но более 9 часов) считается сокращенным отдыхом.",
        "settings_about_section" to "О программе",
        "settings_version_label" to "Версия %s (%s)",
        "form_new_shift" to "Новая смена",
        "form_edit_shift" to "Редактирование смены",
        "form_date_label" to "Дата смены (ДД.ММ.ГГГГ)",
        "form_regular_shift_section" to "Общая Рабочая Смена (Обычная):",
        "form_start_work" to "Начало работы",
        "form_end_work" to "Окончание работы",
        "form_tacho_section" to "Смена по Тахографу (ТАКО):",
        "form_start_tacho" to "Начало Тако",
        "form_end_tacho" to "Окончание Тако",
        "form_driving_hours" to "Часы вождения (ЧЧ:ММ)",
        "form_night_stop" to "Остановка на ночь",
        "form_night_stop_desc" to "Отметьте, если была ночёвка в пути",
        "form_expenses" to "Дорожные расходы (€)",
        "form_submit" to "Подтвердить и сохранить",
        "error_driving_hours" to "Ошибка часов вождения: Введите в формате ЧЧ:ММ (напр., 4:30) или ЧЧ.ММ",
        "error_expenses" to "Ошибка расходов: Введите корректное число (напр., 125.50)",
        "next_shift_start_title" to "Время начала следующей смены:",
        "regular_rest_label" to "Обычный отдых (11 ч)",
        "reduced_rest_label" to "Сокращенный отдых (9 ч)",
        "filter_by_date_title" to "Фильтр смен по датам:",
        "clear_filter_btn" to "Сбросить фильтр",
        "filter_start_label" to "От даты",
        "filter_end_label" to "До даты",
        "filter_start_placeholder" to "Выберите дату",
        "filter_end_placeholder" to "Выберите дату",
        "month_report_title" to "Месячный отчет: %s",
        "period_label" to "Период: %s - %s",
        "week_label" to "Неделя %d (%s-%s): ",
        "week_detail_label" to "смены (обычные) %s, смены (тахограф) %s, вождение %s, ночи %d, расходы %s",
        "total_label" to "Итого:",
        "regular_shifts_total" to "Обычные смены: %s",
        "tacho_shifts_total" to "Смены по тахографу: %s",
        "driving_total" to "Вождение: %s",
        "nights_total" to "Ночи: %d",
        "expenses_total" to "Расходы: %s",
        "tacho_only_mode_desc" to "В сокращённом режиме вводится только время тахографа.",
        "hour_char" to "ч",
        "minute_char" to "мин",
        "no_data" to "нет данных",
        "about_text" to "Driver Shift Tracker - приложение для контроля рабочего времени и соблюдения регламента ЕС 561/2006."
    )

    private val en = mapOf(
        "dashboard_tab" to "Dashboard",
        "shifts_tab" to "Shifts",
        "reports_tab" to "Reports",
        "settings_tab" to "Settings",
        "welcome_title" to "Hello, %s!",
        "welcome_subtitle" to "Time Tracking • EU Working & Rest Time Rules",
        "week_report_title" to "Weekly Report",
        "no_shifts_period" to "No shifts for this period",
        "add_shift_btn" to "Add Shift",
        "weekly_limits_title" to "Weekly Limits (EU Regulation No 561/2006):",
        "limit_shifts_13h" to "Shifts > 13h",
        "limit_driving_9h" to "Driving > 9h",
        "limit_rest_11h" to "Rest < 11h",
        "limit_exceeded" to "Exceeded!",
        "limit_normal" to "Normal",
        "totals_title" to "Totals Summary",
        "metric_driving" to "Driving Time",
        "metric_expenses" to "Total Expenses",
        "metric_regular_shifts" to "Regular Shifts",
        "metric_tacho_shifts" to "Tacho Shifts",
        "metric_nights" to "Night Stops",
        "nights_count" to "%d nights",
        "registered_shifts_week" to "Registered Shifts This Week:",
        "regular_shift_label" to "Regular Shift:",
        "tacho_label" to "Tacho:",
        "driving_label" to "Driving:",
        "duration_label" to "Duration:",
        "night_on_road" to "Night on road",
        "night_at_home" to "Night at home",
        "edit_btn" to "Edit",
        "delete_btn" to "Delete",
        "delete_dialog_title" to "Delete Shift?",
        "delete_dialog_text" to "Are you sure you want to permanently delete the shift for %s from the log?",
        "cancel_btn" to "Cancel",
        "shifts_log_title" to "Shifts Log (%d)",
        "shifts_log_empty" to "The log is empty. Enter your first work shift!",
        "add_shift_action" to "Add Shift",
        "reports_title" to "Summary Reports",
        "reports_range_label" to "Date range for report:",
        "reports_start_label" to "Start period",
        "reports_end_label" to "End period",
        "text_report_title" to "Text Report for Sending",
        "text_report_desc" to "Convenient to copy for sending to the dispatcher via messengers or email.",
        "copy_report_btn" to "Copy Report",
        "preview_report_title" to "Report Preview:",
        "toast_report_copied" to "Report copied to clipboard!",
        "toast_profile_saved" to "Settings saved successfully!",
        "settings_title" to "Settings",
        "settings_profile_section" to "Driver Profile",
        "settings_driver_name" to "Driver's Name",
        "settings_save_btn" to "Save",
        "settings_lang_section" to "Language Selection",
        "settings_lang_ru" to "Русский (RU)",
        "settings_lang_en" to "English (EN)",
        "settings_mode_section" to "App Work Mode",
        "settings_mode_extended" to "Extended (shift + tacho)",
        "settings_mode_shortened" to "Shortened (tacho only)",
        "settings_docs_section" to "EU Regulation No 561/2006",
        "settings_docs_subtitle" to "Key EU regulations for road freight transport:",
        "settings_doc_tacho_title" to "Maximum tacho shift:",
        "settings_doc_tacho_desc" to "Standard shift is 13 hours. Limit can exceed 13 hours (up to 15 hours) at most 3 times per work week.",
        "settings_doc_driving_title" to "Maximum daily driving:",
        "settings_doc_driving_desc" to "Standard daily limit is 9 hours. An increase to 10 hours is allowed at most 2 times per work week.",
        "settings_doc_rest_title" to "Daily rest:",
        "settings_doc_rest_desc" to "Regular rest is at least 11 consecutive hours between work shifts. Rest less than 11 hours (but at least 9 hours) is considered reduced rest.",
        "settings_about_section" to "About the App",
        "settings_version_label" to "Version %s (%s)",
        "form_new_shift" to "New Shift",
        "form_edit_shift" to "Edit Shift",
        "form_date_label" to "Shift Date (DD.MM.YYYY)",
        "form_regular_shift_section" to "Total Work Shift (Regular):",
        "form_start_work" to "Start of Work",
        "form_end_work" to "End of Work",
        "form_tacho_section" to "Tacho Shift (TACO):",
        "form_start_tacho" to "Start of Tacho",
        "form_end_tacho" to "End of Tacho",
        "form_driving_hours" to "Driving Hours (HH:MM)",
        "form_night_stop" to "Night Stop",
        "form_night_stop_desc" to "Check if slept on the road",
        "form_expenses" to "Road Expenses (€)",
        "form_submit" to "Confirm and Save",
        "error_driving_hours" to "Driving hours error: Enter in HH:MM format (e.g., 4:30) or HH.MM",
        "error_expenses" to "Expenses error: Enter a valid number (e.g., 125.50)",
        "next_shift_start_title" to "Next Shift Start Time:",
        "regular_rest_label" to "Regular Rest (11 h)",
        "reduced_rest_label" to "Reduced Rest (9 h)",
        "filter_by_date_title" to "Filter shifts by dates:",
        "clear_filter_btn" to "Clear Filter",
        "filter_start_label" to "From date",
        "filter_end_label" to "To date",
        "filter_start_placeholder" to "Choose date",
        "filter_end_placeholder" to "Choose date",
        "month_report_title" to "Monthly Report: %s",
        "period_label" to "Period: %s - %s",
        "week_label" to "Week %d (%s-%s): ",
        "week_detail_label" to "shifts (regular) %s, shifts (tacho) %s, driving %s, nights %d, expenses %s",
        "total_label" to "Total:",
        "regular_shifts_total" to "Regular Shifts: %s",
        "tacho_shifts_total" to "Tacho Shifts: %s",
        "driving_total" to "Driving: %s",
        "nights_total" to "Nights: %d",
        "expenses_total" to "Expenses: %s",
        "tacho_only_mode_desc" to "In shortened mode only tacho time is input.",
        "hour_char" to "h",
        "minute_char" to "min",
        "no_data" to "no data",
        "about_text" to "Driver Shift Tracker - app for tracking working time and complying with EU Regulation 561/2006."
    )

    fun get(key: String, lang: String): String {
        val map = if (lang == "en") en else ru
        return map[key] ?: ru[key] ?: key
    }

    fun getLocale(lang: String): Locale {
        return if (lang == "en") Locale.ENGLISH else Locale("ru")
    }

    fun formatDate(date: LocalDate, pattern: String, lang: String): String {
        return date.format(DateTimeFormatter.ofPattern(pattern, getLocale(lang)))
    }

    fun formatDateTime(dateTime: LocalDateTime, pattern: String, lang: String): String {
        return dateTime.format(DateTimeFormatter.ofPattern(pattern, getLocale(lang)))
    }
}
